### ISSUE TITLE
Usage with SASS or Nuxt

### ISSUE THREAD

**Issue by nachogarcia** [dimitor115/bootstrap-vue-loader#1]
Hello! The plugin looks nice :)

For me to be able to use it, it would need to be usable with nuxt.js and SASS.

Right now, my bootstrap setup is having in my nuxt.config.js the module 
`'bootstrap-vue/nuxt'` and then import manually the scss, having the config
 
```javascript
  bootstrapVue: {
    bootstrapCSS: false,
    bootstrapVueCSS: false
  }
```

**Comment by dimitor115** [comment]
@nachogarcia Hi! I will check the posibilities how to use it with nuxt.js

**Comment by dimitor115** [comment]
@nachogarcia I have added a description in README how to use it with **nuxt.js**. Also here you have working example nuxt project with the plugin and global modal plugin configured: 
https://github.com/dimitor115/bootstrap-vue-loader/blob/master/dev/nuxt/nuxt.config.js

Let me know if it's working for you! 😄

**Comment by nachogarcia** [comment]
When doing the build, the size of the import was reduced drastically 🥳 even though I use modals and toasters.
 
But when trying to develop (didn't tried the build result yet), many warnings like `"export 'BBtn' was not found in 'bootstrap-vue'` , `"export 'BRadio' was not found in 'bootstrap-vue'` etc. pop up and fails with `Cannot read property 'exports' of undefined` in
```javascript
module.exports = function installComponents (component, components) {

  var options = typeof component.exports === 'function'
    ? component.exports.extendOptions
    : component.options
```

**Comment by dimitor115** [comment]
@nachogarcia The problem here is the `b-btn` alias. Based on the error I think that you are using the `b-btn` alias for `b-button` component and `b-radio` for `b-form-radio`. The aliases are only available with global import. 

Button docs: https://bootstrap-vue.org/docs/components/button#comp-ref-b-button-aliases

Radio docs: https://bootstrap-vue.org/docs/components/form-radio#comp-ref-b-form-radio-aliases

**Comment by nachogarcia** [comment]
Makes sense, I also had issues with the b-navbar-toggle. Replaced them all, altough it would be great to have support at some point.

I'm still having the other error though. I tried not using the toaster or the modal plugin to remove the module but it still doesn't work.

![image](https://user-images.githubusercontent.com/9975630/83403217-8b2e9180-a408-11ea-8df5-6fbf7c5f0ec7.png)

The component that is failing
![image](https://user-images.githubusercontent.com/9975630/83403428-faa48100-a408-11ea-89cd-c48e7f430f13.png)

**Comment by dimitor115** [comment]
@nachogarcia Could to also send how to `Cta.vue` component is implemented, or prepare some reproduction repo? It would be very helpful. I probably need to do some debugging to find and issue and cover this specific case 🤔

**Comment by nachogarcia** [comment]
It's client code, so I can't put it in public. I'm trying to reproduce the issue with dynamic and async components and b-links (which is all it has) but I'm not being able to recreate it in your dev repo

**Comment by nachogarcia** [comment]
I reduced the Cta code to
```
<template>
  <b-link
    :to="to"
  >
    <slot />
  </b-link>
</template>
<script>
export default {
}
</script>
```

And it still fails. Seems like the component to install is undefined, not sure what is causing it in the installation.

I'm debugging it, but so far I'm not being able to pinpoint what is causing the issues :/

**Comment by dimitor115** [comment]
@nachogarcia Has the real component an empty script definition? Like in your example?

**Comment by nachogarcia** [comment]
The real component has many props, mapped getters, etc.  The only thing that doesn't have is name, but it doesn't seem relevant since with that minimal component it still fails.

```javascript
module.exports = function installComponents (component, components) {
  if(!component) {
    console.log(component, components)
```
Looks like the component is undefined and the components is a BLink

![image](https://user-images.githubusercontent.com/9975630/83407960-195b4580-a412-11ea-9847-d8627b7ba283.png)

**Comment by dimitor115** [comment]
Is a CTA.vue an async component? You have written sth about it before. I'm wondering what is different in CTA implementation that causes the component to be undefined 🤔 I will check later the minimal component that you have provided and maybe figured something out what's wrong.

**Comment by nachogarcia** [comment]
It is dynamic (component :is="boolean ? 'b-link' : 'div'") but I don't think this one in particular is async, although some using them are async or inside modals (this component is pretty much everywhere).

Do you think there is some way for me to help by debugging this?

**Comment by dimitor115** [comment]
@nachogarcia for this moment I think not. I will ping you after some debugging this evening 😸

**Comment by dimitor115** [comment]
@nachogarcia The problem was SSR. You couldn't reproduce it in my repo because (don't know why), nuxt was in SPA mode there. I've fixed the loader code to work properly with SSR and will release a new version in the morning. 

BTW, as I see in your screenshots you are using sth like this: 
```
<component
    :is="hasUrlData ? 'b-link' : 'div'"
    v-if="isLink">
</component>
```
This usage of `b-link` won't be detected by the loader. You will need to import the BLink manually. 
You can do it in the Cta.vue component: 
```
<script>
  import {BLink} from 'bootstrap-vue'
  export default {
    components: {BLink},
    props: ['hasUrlData', 'isLink']
  }
</script>
```
Or globally in your nuxt.config.js
```javascript
modules: [
    'bootstrap-vue/nuxt',
  ],
  bootstrapVue: {
    components: ['BLink']
  },
```

**Comment by dimitor115** [comment]
@nachogarcia Please check the new 1.0.3 version! 😸

**Comment by nachogarcia** [comment]
Now the build works, but nothing is working - BImgLazy, BAlert, cols, dropdowns... Even stuff that isn't from bootstrap like the select2.

There is no error logged anywhere.

Looks like if I remove the module `'bootstrap-vue/nuxt'` everything works again, but since I use toasts and modals that isn't enough for me.

**Comment by nachogarcia** [comment]
Uhm, weird. I put back the module and everything works fine. Maybe the npm start didn't work for some reason. Now everything works fine.

Will keep testing it for a bit and see if it works consistently :) thanks a lot!

**Comment by dimitor115** [comment]
@nachogarcia Cool! Let me know after some time if it's working as expected and If so, I will close this issue 😄

**Comment by nachogarcia** [comment]
![image](https://user-images.githubusercontent.com/9975630/83493341-ed44d080-a4b4-11ea-8d50-f3f7eb6c8120.png)

The package must be installed as a dependency (not devDependency) (Already changed it)

The stat size of the bundle is almost 1MB less so it's working great.

But with the production build, I get the same error as before

![image](https://user-images.githubusercontent.com/9975630/83494492-a5bf4400-a4b6-11ea-9dd8-b5d217b4531b.png)

**Comment by dimitor115** [comment]
@nachogarcia ok, looking at it. I have an idea 😄

**Comment by dimitor115** [comment]
@nachogarcia With version 1.0.4 it's working great also in build version.
The plugin for sure should be a devDependency, I've checked it's working great in nuxt.

**Comment by nachogarcia** [comment]
I'm trying the new version.

The devDependency... maybe it has relation with how I create the bundle:

Dockerfile

```
FROM node:12.16 as builder

ENV NODE_ENV development

RUN mkdir -p /usr/src/nuxt-app
WORKDIR /usr/src/nuxt-app

COPY . ./
# RUN npm ci --no-progress We use cached ci node_modules to improve build time

ENV NODE_ENV production

RUN npm run build && \
  npm prune --production
# ---
FROM node:12.16-alpine

ENV NODE_ENV production

COPY --from=builder --chown=node:node /usr/src/nuxt-app /usr/src/nuxt-app

USER node
WORKDIR /usr/src/nuxt-app
EXPOSE 3000
ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

CMD ["node", "./nuxt", "start"]
```

**Comment by dimitor115** [comment]
Hmmm, maybe the problem is here with `# RUN npm ci --no-progress We use cached ci node_modules to improve build time` ? 🤔 Maybe the new package is not in cache yet?

**Comment by nachogarcia** [comment]
Nope, it is there for sure. I was thinking in the `npm prune --production`

**Comment by dimitor115** [comment]
Yes, it could be this. Why you need it? To reduce size of the docker container?

**Comment by nachogarcia** [comment]
Yeah, I don't want devDependencies in production - since they wouldn't be only for development.

This is working great for now! 👯

**Comment by nachogarcia** [comment]
Already merged to our develop branch and no issues for now. If something arises I will let you know :)

You should start to see downloads now! 👍
