### ISSUE TITLE
Components not registering

### ISSUE THREAD

**Issue by Sunhat** [dimitor115/bootstrap-vue-loader#16]
Following the instructions for nuxt, the bundle is smaller, but none of the components are registered, no errors, aside from component not registered

nuxt@2.11
bootstrap-vue@2.5.0
bootstrap-vue-loader@1.0.4

**Comment by dimitor115** [comment]
@Sunhat 
I can't help you whitout some minimal reproduction repo. Please also check the example nuxt configuration https://github.com/dimitor115/bootstrap-vue-loader/tree/master/dev/nuxt where everything seems to work fine. Hope it helps!
