### ISSUE TITLE
Doesn't work with "bootstrap-vue": "^2.21.1",

### ISSUE THREAD

**Issue by solancer** [dimitor115/bootstrap-vue-loader#26]
loader breaks with "bootstrap-vue": "^2.21.1",

**Comment by dimitor115** [comment]
@solancer I will take a look. Thanks for the information.

**Comment by nachogarcia** [comment]
I see that in 1.0.6 bootsrap-vue was changed so it no longer admits compatible versions with ^2.21.2.

May I ask why? Wouldn't this create duplicated bootstrap-vue versions if we're not using that exact one? I think it's better to leave the ^.

BTW I didn't have any issues with the loader :S
